FROM wolfitem/phpstorm
MAINTAINER wolfitem <wei.wu86@hotmail.com>

USER root

RUN curl 'http://7xi48y.com2.z0.glb.qiniucdn.com/WebIde80.tar.gz' > /tmp/WebIde80.tar.gz && tar -zxvf /tmp/WebIde80.tar.gz && rm /tmp/WebIde80.tar.gz && sudo mv .WebIde80 /home/developer/.Webide80

USER developer


